### ISSUE TITLE
Ordine liste

### ISSUE THREAD

**Issue by vi-enne** [indecis-it/data#12]
Propongo temporaneamente il seguente ordine per le liste:

Cdx
FdI
Lega
FI
Noi Moderati

Csx
PD
AVS
+E
IC

M5S

Az-IV

Altre liste, in attesa di sapere quali si presenteranno.

**Comment by dennisangemi** [comment]
Ciao @vi-enne ordine di cosa? Per cosa? Noccapito

**Comment by vi-enne** [comment]
Nella visualizzazione finale: al momento l'ordine mi sembra pseudo casuale.

**Comment by dennisangemi** [comment]
> Nella visualizzazione finale: al momento l'ordine mi sembra pseudo casuale.

Allora se è qualcosa che riguarda il sito (e quindi @angelogulina ) sposterei issue in repo indecis.it

**Comment by angelogulina** [comment]
Ciao @vi-enne – banalmente, sono ordinate in base al loro id (da foglio `lists`) 🙈 

Se non è troppo complicato, cambierei lato Google Sheet. (In questo caso, la issue può restare qui)

**Comment by angelogulina** [comment]
PS: il codice esclude quelle per le quali non abbiamo simbolo.

**Comment by dennisangemi** [comment]
> Se non è troppo complicato, cambierei lato Google Sheet. (In questo caso, la issue può restare qui)

Ciao @angelogulina, ho seguito il tuo consiglio e ho modificato ordine dallo sheet (foglio `🗳️ lists` ) secondo le indicazioni di @vi-enne . Tuttavia non sono super convinto dell'ordine. 

La mia proposta:
Sarebbe il caso di introdurre un ordine random ad ogni refresh di pagina? 

@angelogulina è possibile introdurre una feature di questo tipo?
@vi-enne che te ne pare?

La mia proposta ancora più folle:
dare la possibilità all'utente di spostare le colonne per permettere di accostare due liste di cui si vogliono paragonare i programmi (es. Azione e FdI, attualmente ultimo e primo)

---

@vi-enne perchè hai suggerito proprio questo ordine?

**Comment by angelogulina** [comment]
Grazie @dennisangemi. 

> Sarebbe il caso di introdurre un ordine random ad ogni refresh di pagina?

È possibile. Delego a voi la scelta su come impostare l'ordine.

> dare la possibilità all'utente di spostare le colonne per permettere di accostare due liste di cui si vogliono paragonare i programmi (es. Azione e FdI, attualmente ultimo e primo)

Spostare sarebbe dispendioso in termini di tempo, sia per UI che logica. Potremmo invece optare per permettere una selezione delle liste, così da filtrare quelle non scelte. (Una sorta di checklist). Se optiamo per intervenire lato UI, creiamo una issue su repo principale e assegnate a me.

**Comment by vi-enne** [comment]
> @vi-enne perchè hai suggerito proprio questo ordine?

Liste raggruppate per coalizione e peso nei sondaggi.

**Comment by dennisangemi** [comment]
> Liste raggruppate per coalizione e peso nei sondaggi.

Makes sense. Grazie @vi-enne

**Comment by vi-enne** [comment]
Grazie, chiudo per ora :)
