### ISSUE TITLE
Migliorare il foglio status/glossary

### ISSUE THREAD

**Issue by vi-enne** [indecis-it/data#13]
Due suggerimenti per il foglio status/glossary:

- [ ] Aggiungere la colonna category, in modo da accorgersi se a un subject è stata assegnata la category sbagliata.
- [ ] Idealmente, fare in modo che il foglio status/glossary popoli i fogli c-lista, e non viceversa.

**Comment by dennisangemi** [comment]
Ciao @vi-enne ho apportato queste modifiche al foglio status:
- se in `c-lista` c'è un subject con icone diverse sotto la stessa lista allora in `status` comparirà una cella colorata NERO il cui contenuto sarà dato dalle diverse posizioni concatenate (e.g. `yellow,red`);
- se non abbiamo compilato la cella che fa riferimento all'icona di un subject per una determinata lista, allora il foglio status restituirà il messaggio `NF` (che l'ho immaginato come `NOT FOUND`);
- le celle colorate in giallo/verde/rosso di `status` non corrispondono ad errori e quindi possiamo stare tranquilli

**Comment by dennisangemi** [comment]
> Idealmente, fare in modo che il foglio status/glossary popoli i fogli c-lista, e non viceversa

Ciao @vi-enne , adesso il foglio `🔎 glossary` non si popola automaticamente. 

Se per te le modifiche apportate a glossary e status sono ok, chiuderei.

p.s. probabilmente tra non molto faremo a meno del foglio status per individuare gli errori perchè tratteremo le relazioni tra items e categories come da #15

**Comment by vi-enne** [comment]
Mi sembra ok.
Lascerei il foglio status, è comunque un ottimo riepilogo.

Grazie!
