### ISSUE TITLE
relazioni tra items e categories

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#15]
In fase di raccolta dati si è notato che un `item` può appartenere a diverse `categories`. [Qui un esempio](https://github.com/indecis-it/indecis.it/issues/3#issuecomment-1218292432) di @vi-enne. Attualmente, per assegnare un `item` a più `categories`, si duplicano le righe nei fogli `i-list` selezionando categorie differenti (una per ogni riga)

### Problema
Questo processo rallenta la raccolta dati e genera errori (e.g. capita di assegnare per una stessa lista e per uno stesso item delle posizioni differenti al variare categoria selezionata).

### La mia proposta di soluzione
- Eliminare colonna `category` dai fogli `i-list` così da compilare un item una sola volta (anche se esso appartiene a più categorie);
- Creare un nuovo foglio in cui mettere in relazione gli` items` con le `categories`. Il foglio potrebbe chiamarsi `relic` (che nella mia testa starebbe per "relations items categories") e potrebbe avere una struttura di questo tipo (con id, slug e tutto quello che serve)

| subject | category |
| --- | --- |
Alloggi popolari | economia |
Alloggi popolari | servizi |
flat tax | economia |
nucleare | economia |
nucleare | ambiente |

### Problemi che potrebbero sorgere
Se si procede in questo modo, il foglio `items` che fa merging dei fogli `i-list` sarebbe privo della colonna `category` (esattamente come i fogli `i-list`) e questo creerebbe senza dubbio problemi per @angelogulina lato codice. Attualmente non mi viene in mente una soluzione su google sheet per mantere invariato il foglio `items` ed eliminare contemporaneamente la fastidiosa colonna `category` in `i-list`. 

Di seguito due domande:
- @angelogulina se accettassimo la mia proposta, per te sarebbe complicato assegnare uno stesso item a più categorie lato codice sfruttando il foglio `relic`? 
- @vi-enne @LorenzoRuff vi vengono in mente soluzioni (google sheet) per mantenere invariato il foglio `items` ed eliminare colonna `category` da `i-list`?

IMHO `relic` sarebbe un modo ordinato per tracciare le relazioni ma se questo crea troppi problemi ad @angelogulina allora forse è meglio lasciare tutto così com'è.

**Comment by dennisangemi** [comment]
Aggiornamenti: Indipendentemente dalla strada che seguiremo ho creato foglio [`🔗 relic`](https://docs.google.com/spreadsheets/d/13YKVLtayxu0m2keOi1KHsLJqoshc9P279RLJ_sdhnAk/edit#gid=2021671775).

**Comment by dennisangemi** [comment]
Ciao @angelogulina, per adesso ti chiederei di occuparti solo di questa issue (se/quando puoi). Grazie e baci

**Comment by vi-enne** [comment]
Possiamo anche solo decidere di assegnare a un subject una sola categoria, ovvero la principale.
Ad esempio, ho l'impressione che Nucleare riguardi più ambiente che economia.

**Comment by dennisangemi** [comment]
> Possiamo anche solo decidere di assegnare a un subject una sola categoria, ovvero la principale. Ad esempio, ho l'impressione che Nucleare riguardi più ambiente che economia.

Vero @vi-enne , la difficoltà si avrebbe ad esempio per "stipendio docenti" che sarebbe opportuno a segnare sia a economia che a scuola.

**Comment by vi-enne** [comment]
Vero, ma si può sempre cambiare dopo.
Comunque lo metterei in scuola, visto che i programmi dei partiti lo mettono in scuola :)

**Comment by dennisangemi** [comment]
Alla luce di #16 e per ragioni di flessibilità abbiamo ritenuto opportuno mantenere tab relic da utilizzare insieme a wide. Queste modifiche non alterano il file di output items che verrà utilizzato per il sito. Chiudo, al massimo si riapre ;)

Come sempre, grazie @vi-enne
