### ISSUE TITLE
problemi items.json

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#2]
Ciao @angelogulina mi confermi che adesso il file `items.json `è valido?

Il comportamento di questo file è un po' sospetto. 
Quando uso https://jsonformatter.curiousconcept.com/ succede questo:

- validazione passata se copio e incollo il file
- validazione **non** passata se copio l'url del file

## Note aggiuntive
Per quanto riguarda il `]` finale:
- se eseguo lo script in locale, miller lo inserisce
- se eseguo script tramite action, miller non lo inserisce :|

Probabilmente in locale ho installato versione di miller più recente successiva rispetto a quella che usa l'action. Per adesso carico il file generato in locale.

**Comment by angelogulina** [comment]
@dennisangemi mi sembra tutto funzioni bene adesso. Grazie!

---

_OT_

Ho notato che alcune celle `endorsement` non sono ancora popolate (va bene così). Non avendo però una icona da mostrare, queste righe non saranno mostrate su UI.

Un'altra opzione può essere di mostrarle ma con un punto interrogativo o simile, per incoraggiare il crowdsourcing. Una cosa che può essere implementata successivamente. Fatemi sapere cosa ne pensate.

/cc @vi-enne

**Comment by dennisangemi** [comment]
visto che l'ultimo run dell'action non ha creato problemi al file `items.json` chiudo questa issue. Thx @angelogulina per il supporto <3
