### ISSUE TITLE
installare versione di miller recente

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#22]
Ciao @aborruso, ti disturbo per commissionarti una missione speciale.

Questo è il repo in cui buttiamo i dati di indecisit. Usiamo [questa action ](https://github.com/indecis-it/data/blob/main/.github/workflows/main.yml)per fare tante cose ma a noi attualmente interessano gli step in cui si [installa miller ](https://github.com/indecis-it/data/blob/main/.github/workflows/main.yml#L32)e in cui si [convertono i csv in json](https://github.com/indecis-it/data/blob/main/.github/workflows/main.yml#L45). 

Il problema: ogni tanto miller si mangia un `]` alla fine del json.

A giudicare dal [log dell'action ](https://github.com/indecis-it/data/runs/8122215958?check_suite_focus=true#step:8:12), credo che incappiamo in [questo vecchio bug](https://github.com/johnkerl/miller/issues/368) perchè pare che l'action installi una versione vecchiotta di miller. 

Io [ho provato a scopiazzare ](https://github.com/indecis-it/data/blob/main/.github/workflows/main.yml#L36)dai tuoi script per provare ad installare una versione più aggiornata di miller ma [non sono riuscito nell'impresa ](https://github.com/indecis-it/data/runs/8124078977?check_suite_focus=true#step:9:12)

Potresti svelarci il segreto per installare una versione recente di miller tramite gh action? Grazie ;)

**Comment by aborruso** [comment]
Ciao @dennisangemi mi puoi allegare uno dei file JSON di input che manda in errore lo script?

**Comment by dennisangemi** [comment]
Ciao @aborruso , questo [input.csv](https://github.com/indecis-it/data/files/9469274/input.csv) è il csv che convertito in json è privo di una `]`.

Il comando che lancio per eseguire la conversione è

```bash
mlr --icsv --ojson --jlistwrap --jvstack cat input.csv > output.json
```

Ottengo questo warning/errore

```
mlr: unmatched double quote at line 12
```

e il json in output non ha la `]` alla fine

**Comment by aborruso** [comment]
caro @dennisangemi non ho errori, né con la versione 5.10.2, né con la 6.4.0.

Ho visto la tua action. Pesca una versione di Miller vecchia, la 5.7.

L'ho aggiornata, adesso anche quella è 5.10.2. Riprova a lanciare l'action

**Comment by dennisangemi** [comment]
Ciao @aborruso, [grazie per l'aggiornamento](https://github.com/ondata/covid19italia/commit/16b6b40236811d3d5bddbf8324dda60519cbf2d4). 

Non riesco comunque a installare eseguibile tramite action perchè ottengo [questo errore ](https://github.com/indecis-it/data/runs/8124078977?check_suite_focus=true#step:9:12).

Provavo ad installare con questo codice qui https://github.com/indecis-it/data/blob/main/.github/workflows/main.yml#L36

p.s. abbiamo risolto il problema del json rotto con la #23 ma sarei comunque curioso di capire come installare eseguibile <3

**Comment by aborruso** [comment]
Ciao @dennisangemi ,
penso che sia una questione di variabili di ambiente.

Devi esportare il PATH nello stesso run. Perché la variabile poi sparisce.

Quindi da

```yml
      - name: Test Install miller
        run: |-
          curl -kL "https://raw.githubusercontent.com/ondata/covid19italia/master/bin/mlr" > mlr
          mkdir -p ~/bin
          cp mlr ~/bin
          cd ~/bin
          chmod +x mlr
          export PATH=$PATH:~/bin
      
      - name: Build json
        run: |-
          chmod +x script/convert.sh
          script/convert.sh
```

a

```yml
      - name: Test Install miller
        run: |-
          curl -kL "https://raw.githubusercontent.com/ondata/covid19italia/master/bin/mlr" > mlr
          mkdir -p ~/bin
          cp mlr ~/bin
          cd ~/bin
          chmod +x mlr
         
      - name: Build json
        run: |-
          export PATH=$PATH:~/bin
          chmod +x script/convert.sh
          script/convert.sh
```

**Comment by dennisangemi** [comment]
Arcano svelato! Grazie grazie grazie @aborruso <3
