### ISSUE TITLE
fix encoding

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#27]
Ciao @vi-enne,
credo di aver introdotto un problema di encoding mentre giocavo con lo script R. vd https://www.indecis.it/tematica/sanita

Per caso hai idee sul come risolvere e forzare l'UTF-8 ovunque?

**Comment by vi-enne** [comment]
Al volo, puoi provare a usare `write.csv` invece di `write_csv`, con  argomento `fileEncoding = "UTF-8"`

es.

`write.csv(data,"data.csv",fileEncoding = "UTF-8")`

**Comment by aborruso** [comment]
@dennisangemi se conosci l'encoding dei file di output, puoi convertire tutto in batch a riga di comando con iconv.

Se fosse ad esempio  iso8859-1

```
iconv -t UTF-8 -f iso8859-1 input.csv >out.csv
```

**Comment by dennisangemi** [comment]
Grazie mille @vi-enne @aborruso 

> Al volo, puoi provare a usare write.csv invece di write_csv

Funziona perfettamente per i csv (grazie!) ma non per i json.

Torno a generare i json con miller (grazie @aborruso ) fin quando non capiamo come correggere encoding dei file json generati da R.

**Comment by aborruso** [comment]
> Funziona perfettamente per i csv (grazie!) ma non per i json.

Deve funzionare in entrambi i casi. Ma devi essere certo dell'encoding di input.
Se mi vuoi allegare uno dei file JSON, da convertire in UTF-8, vai pure.

**Comment by aborruso** [comment]
@dennisangemi scusami non leggere nemmeno il mio messaggio. Non avevo capito la tua risposta. Tu parlavi di R.

Ignorami

**Comment by dennisangemi** [comment]
Risolto! Grazie @aborruso @vi-enne 

chiudo ;)
