### ISSUE TITLE
Aggiungere nome per source

### ISSUE THREAD

**Issue by angelogulina** [indecis-it/data#30]
Nella UI ci sarebbe l'esigenza di mostrare la fonte degli articoli di approfondimento (ad es., `Contributi per edilizia scolastica su Wikipedia`). Per avere `su Wikipedia` bisognerebbe conoscere la fonte del link.

La stessa cosa per gli articoli di Pagella Politica

### Proposta

Su `wide`:
1. rinominare colonna `info` in `info_url` (resta `url` su `glossary`)
2. aggiungere colonna `info` (diventa `source` su `glossary`) (ad es., `Wikipedia`)
3. aggiungere colonna `info_title` (diventa `title` su `glossary`) (ad es., `Edilizia scolastica`, ossia il titolo dell'articolo)

Su `press`:
1. aggiungere `source` (ad es., `Pagella Politica`)

**Comment by angelogulina** [comment]
@dennisangemi puoi dirmi cosa ne pensi di questa proposta. Principalmente, se è chiaro cosa serve? (Il come, ossia la proposta, puoi anche variarla se hai idee migliori)

**Comment by angelogulina** [comment]
@dennisangemi per darti un'idea visuale di cosa voglio ottenere:

||
|-|
|![Screenshot 2022-09-07 at 09 17 31](https://user-images.githubusercontent.com/4223655/188813994-fd3d23bf-b13f-4f93-a0e0-84c25e04d860.png)|

La parte sottolineata è quella che manca come fonte dati.

**Comment by dennisangemi** [comment]
Chiarissimo @angelogulina, lo faccio in mattinata

**Comment by angelogulina** [comment]
Grazie, @dennisangemi – ho aggiunto un punto 3 per `wide`.

**Comment by dennisangemi** [comment]
@angelogulina posso committare i nuovi dati?

**Comment by angelogulina** [comment]
Mi sembra tutto perfetto. Grazie per la velocità @dennisangemi!

**Comment by dennisangemi** [comment]
Ottimo, grazie del feedback @angelogulina ! chiudo ;)
