### ISSUE TITLE
Alcuni subject non sono consultabili dal sito

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#32]
Esempio: green pass oppure obbligo vaccinale

Forse un problema con lo script di reshaping?  Ci torno

**Comment by vi-enne** [comment]
Sono gli unici due.

Credo che il problema sia alla [riga 36](https://github.com/indecis-it/data/blob/fd3ad43d310dab544f05cea12a037a0b79368637/script/reshape.R#L36) di `reshape.R`.

**Comment by vi-enne** [comment]
Risolto: il problema era nelle maiuscole Green **P**ass vs Green **p**ass.

Potremmo pensare di migliorare il codice rendendo le stringhe dei subject minuscole, ma potrebbe causare ancora più problemi.

Chiudo dopo run.

**Comment by dennisangemi** [comment]
Grazie mille @vi-enne !
