### ISSUE TITLE
[contributing] Come incoraggiare/permettere crowdsourcing

### ISSUE THREAD

**Issue by angelogulina** [indecis-it/data#5]
Uscendo con l'MVP, è probabile che qualche persona voglia suggerire delle modifiche o integrazioni.

Con quali modalità possiamo permettere la contribuzione? Alcune idee (non mutualmente esclusive):

1. Pull request (ma che punta a cosa?)
2. Issues
3. Commenti sullo Sheet (in questo caso, bisognerebbe renderlo pubblico con Commenti/Suggerimenti)

Tasks:

- [ ] testo per contribution @angelogulina 
- [ ] testo per code of conduct @angelogulina 
- [x]  abilitare commenti su sheet (se non sono già abilitati per chiunque) @dennisangemi 
- [x] aggiungere istruzioni per data entry su gsheet @dennisangemi

**Comment by angelogulina** [comment]
@dennisangemi @vi-enne, se avete (altre) idee, o se pensate non sia una buona idea, scrivete qui.

Grazie!

**Comment by dennisangemi** [comment]
Ciao @angelogulina, mi sembra perfetto. Io mi prendo il task
- [ ] abilitare commenti su sheet (se non sono già abilitati per chiunque)

**Comment by dennisangemi** [comment]
Ho aggiunto le istruzioni per effettuare data entry su [sheet qui ](https://docs.google.com/spreadsheets/d/13YKVLtayxu0m2keOi1KHsLJqoshc9P279RLJ_sdhnAk/edit#gid=734919268&range=B29)

**Comment by dennisangemi** [comment]
Mi pare che il data entry sia stato completato! Chiudo
