### ISSUE TITLE
empty endorsement

### ISSUE THREAD

**Issue by dennisangemi** [indecis-it/data#7]
Ho notato che alcune celle `endorsement` non sono ancora popolate (va bene così). Non avendo però una icona da mostrare, queste righe non saranno mostrate su UI.

Un'altra opzione può essere di mostrarle ma con un punto interrogativo o simile, per incoraggiare il crowdsourcing. Una cosa che può essere implementata successivamente. Fatemi sapere cosa ne pensate.

/cc @vi-enne

_Originally posted by @angelogulina in https://github.com/indecis-it/data/issues/2#issuecomment-1220323145_

**Comment by vi-enne** [comment]
Al momento non si possono inserire su gsheet valori diversi da green, yellow, red, ovvero i valori di `endorsement` disponibili. Le ho lasciate vuote perché al momento non le ho trovate nel programma, ma potrebbero parlarne in altre fonti (tweet, dichiarazioni).

Soluzioni:
- aggiungere un nuovo valore di `endorsement` -> ?
- lasciarle vuote o gialle

**Comment by dennisangemi** [comment]
Io voto per "lasciarle gialle" a patto che dichiariamo in qualche posto il significato delle icone. In tal caso giallo vorrebbe dire "nessuna posizione oppure posizione neutra oppure non siamo riusciti a trovare informazioni a riguardo"

**Comment by angelogulina** [comment]
@vi-enne e @dennisangemi, mi pare una soluzione solida.

Il [README](https://github.com/indecis-it/indecis.it#come) dice (per il giallo): _il tema non è presente nelle fonti a nostra disposizione_. Più sotto, invitiamo chi vuole contribuire a _suggerire una nuova fonte che possa colmare le conoscenze mancanti_.

Direi quindi di andare con il giallo (se siete d'accordo)

![](https://media.giphy.com/media/JtGFTVGrwOL3rJGOgS/giphy.gif)

**Comment by dennisangemi** [comment]
> Il [README](https://github.com/indecis-it/indecis.it#come) dice (per il giallo): il tema non è presente nelle fonti a nostra disposizione. Più sotto, invitiamo chi vuole contribuire a suggerire una nuova fonte che possa colmare le conoscenze mancanti.
Direi quindi di andare con il giallo (se siete d'accordo)

Ottimo! Grazie mille @angelogulina . Per me è super ok

**Comment by angelogulina** [comment]
Modificato con https://github.com/indecis-it/indecis.it/commit/3e1e516460402805069df21953968bc061a688a1.

Grazie e chiudo.
